### ISSUE TITLE
How to Delete a Person (Student/Faculty)

### ISSUE THREAD

**Issue by kevindionr** [parkerj/eduTrac-SIS#90]
Is there a way to delete a person (student/faculty)? I created some demo persons and would like to delete them from the system.

**Comment by nomadicjosh** [comment]
No, in order to safeguard student info and make sure it is not deleted by mistake. But you can go into the database, go to the person table and delete the records. When they are deleted, all other records are deleted unless there are student records such as student acad records. If student acad records exist, then they must be deleted before the person record can be deleted. Student acad records can be deleted via the SPRO screen.

Someone suggested allowing the deletion of person records only if the site is in DEV mode in which only an administrator can set. So, that is something that may be implement in the future.
